version: "3.3"

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRESQL_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # install requirements.txt
    
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev

    depends_on:
      - db
volumes:
  postgres_data:

networks:
  default:
      name: hello_fastapi
